/* eslint-disable @typescript-eslint/no-empty-object-type */
// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
}
